config/routes.rb
Rails.application.routes.draw do
  resources :user_topics
  resources :user_boards
  resources :posts
  resources :boards do
    resources :topics
  end
  get '/myposts', to: 'posts#user', as: 'user_posts'
  get '/news', to: 'application#news', as: 'news'
  get '/about', to: 'application#about', as: 'about'
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  devise_scope :user do
    get '/auth/:provider/callback', to: 'users/sessions#create'
  end
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end
  

end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  belongs_to :user
  belongs_to :board

  validates :title, presence: true
  validates :body, presence: true

  def created
    created_at.strftime("%-d %B, %Y: %l:%M%P")
  end

  def edited
    updated_at.strftime("%-d %B, %Y: %l:%M%P")
  end

  def num_of_responses
    posts.count
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @board = Board.find(params[:board_id])
    @topics = @board.topics.shuffle
    @user = current_user
  end

  def show
    @topic = Topic.find(params[:id])
    @board = Board.find(params[:board_id])
    @user = current_user
    if session[:failed_post]
      @post = Post.create(session.delete(:failed_post))
    else
      @post = Post.new
    end
    
    @user_topic = UserTopic.new
  end

  def new
    @board = Board.find(params[:board_id])
    if current_user
      
      @topic = Topic.new

    
      @user = current_user
    else
      redirect_to board_path(@board), alert: "You must log in to make a topic"
    end
  end

  def create
    topic = Topic.create(topic_params)
    if topic.valid?
      redirect_to board_topic_path(topic.board, topic)
    else
      @board = Board.find(params[:board_id])
      @user = current_user
      @topic = topic      
      render :new

    end
  end

  def edit
    @user = current_user
    @topic = Topic.find(params[:id])
    @board = @topic.board
    unless current_user == @topic.user || current_user == @board.owner
      return redirect_to board_topic_path(@board, @topic), alert: "You don't have permission to edit this topic"
    end
  end

  def update
    
    topic = Topic.find(params[:id])
    unless current_user == topic.user || current_user == topic.board.owner
      return redirect_to board_topic_path(topic.board, topic), alert: "You don't have permission to edit this topic"
    end
    if topic.update(topic_params)
      redirect_to board_topic_path(topic.board, topic)
    else
      render :edit, alert: "Error updating topic"
    end
  end

  def destroy
    
    topic = Topic.find(params[:id])
    board = topic.board
    if topic.user == current_user || board.owner == current_user
      topic.destroy
      redirect_to board_path(board), alert: "Topic successfully destroyed"
    else
      redirect_to board_topic_path(board, topic), alert: "You don't have permission to destroy this topic"
    end
  end

  private
    def topic_params
      params.require(:topic).permit(:user_id, :title, :body, :board_id)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for [board, topic]  do |f| %>
  <%= render 'layouts/error_messages', :target => topic %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.hidden_field :user_id, value: user.id %>
  <%= f.hidden_field :board_id, value: board.id %>

  <%= f.submit %>
<% end %>

app/views/topics/_topic.html.erb
<h5><%= topic.title %></h5>
<small><strong>ID: <%= topic.id %> | <%= topic.created %></strong></small>
<p><%= Rinku.auto_link(simple_format(topic.body), :all, 'target="_blank"').html_safe %></p>
<% if user == topic.user || user == board.owner %>
  <%= link_to "Edit", edit_board_topic_path(board,topic) %>
  <%= link_to "Delete", board_topic_path(board,topic), :method => :delete, data: {confirm: "Are you sure?"} %>
<% end %>

app/views/topics/edit.html.erb
<%= render partial: 'form', locals: {:topic => @topic, :user => @user, :board => @board} %>

app/views/topics/index.html.erb
<h6><%= link_to @board.title, board_path(@board) %></h6>
<% if @user %>
  <div align="center">
    <strong><%= link_to "CREATE NEW TOPIC", new_board_topic_path(@board) %></strong>
  </div>
<% end %>
<% @topics.each do |topic| %>
  <%= render partial: 'topic', locals: {:topic => topic, :board => @board, :user => @user} %>
  <small><%= topic.posts.count %> responses</small><br>
  <a href="<%= board_topic_path(@board, topic) %>"><button>View</button></a>
<% end %>

app/views/topics/new.html.erb
<%= render partial: 'form', locals: {:topic => @topic, :user => @user, :board => @board} %>

app/views/topics/show.html.erb
<h6><%= link_to @board.title, board_path(@board) %></h6>
<a name="OP"></a>
<%= render partial: 'topic', locals: {:topic => @topic, :board => @board, :user => @user} %>
<% if @user && !@user.user_topics.pluck(:topic_id).include?(@topic.id) %>
  <%= render partial: 'user_topics/form', locals: {:topic => @topic, :user => @user} rescue "" %>
<% end %>

<%= link_to "Back", board_topics_path(@board) %>
<h5>Responses:</h5>
<% @topic.posts.each do |post| %>
  <%= render partial: 'posts/post', locals: {:post => post} %>
  
  <hr>
<% end %>

<h5>Reply:</h5>

<%= render partial: 'posts/form', locals: {:topic => @topic, :user => @user} rescue "You must login to respond." %>