config/routes.rb
Rails.application.routes.draw do
  resources :user_topics
  resources :user_boards
  resources :posts
  resources :boards do
    resources :topics
  end
  get '/myposts', to: 'posts#user', as: 'user_posts'
  get '/news', to: 'application#news', as: 'news'
  get '/about', to: 'application#about', as: 'about'
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  devise_scope :user do
    get '/auth/:provider/callback', to: 'users/sessions#create'
  end
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end
  

end

app/models/board.rb
class Board < ApplicationRecord
  has_many :topics, dependent: :destroy
  has_many :posts, through: :topics
  belongs_to :owner, class_name: "User"

  validates :title, presence: true
  validates :description, presence: true

  def self.random_topics
    all.map(&:topics).flatten.shuffle.first(10)
  end

  def self.recent_topics
    all.map(&:topics).flatten.sort {|a, b| a <=> b}.reverse.first(10)
  end

  def last_10_topics
    posts.order("id DESC").map(&:topic).uniq.first(10)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
    @user = current_user || User.new
  end

  def show
    @board = Board.find(params[:id])
    @topics = @board.last_10_topics
    @user = current_user
  end

  def new
    if current_user
      @board = Board.new
      @user = current_user
    else
      redirect_to boards_path, alert: "You need an account to make a board"
    end
  end

  def create
    board = Board.create(board_params)

    if board.valid?
      redirect_to board_path(board)
    else
      @board = board
      @user = current_user
      render :new, alert: "There was an error processing your board"
    end
  end

  def edit

    @board = Board.find(params[:id])
    unless current_user && current_user == @board.owner
      return redirect_to boards_path, alert: "You don't have permission to edit this board"
    end
    @user = current_user
  end

  def update
    board = Board.find(params[:id])
    if board.update(board_params)
      redirect_to board_path(board)
    else
      render :edit, alert: "There was an error updating your board"
    end
  end

  def destroy

    board = Board.find(params[:id])
    if board.owner == current_user
      board.destroy
      redirect_to boards_path, alert: "Board destroyed"
    else
      redirect_to boards_path, alert: "You do not have permissions to delete that board"
    end
  end

  private
    def board_params
      params.require(:board).permit(:owner_id, :title, :description)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<h4><%= link_to board.title, board_path(board) %></h4> 

<p><%= board.description %></p>
<a href="<%= board_path(board) %>" class="u-pull-right"><button>View</button></a><br>
<% if user == board.owner %>

  <%= link_to "Edit", edit_board_path(board) %><br>
  <%= link_to "Delete",board_path(board), :method => :delete, data: {confirm: "Are you sure?"} %>
  
<% end %>
<hr>

app/views/boards/_form.html.erb
<%= form_for(board) do |f| %>
  <%= render 'layouts/error_messages', :target => @board %>
    
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :description %><br>
  <%= f.text_field :description %><br>
  
  <%= f.hidden_field :owner_id, value: user.id %><br>
  <%= f.submit %>
<% end %>

app/views/boards/edit.html.erb
<%= render partial: 'form', locals: {:board => @board, :user => @user} %>

app/views/boards/index.html.erb
<% @boards.each do |board| %>
  <%= render partial: 'board', locals: {:board => board, :user => @user} %>
<% end %>
<%= link_to "Create New Board", new_board_path %>

app/views/boards/new.html.erb
<%= render partial: 'form', locals: {:board => @board, :user => @user} %>
<%= link_to "Cancel", boards_path %>

app/views/boards/show.html.erb
<div align="center">
  <h2><%= @board.title %></h2>

  <h5><%= @board.description %></h5>
  <% if @user == @board.owner %>

    <%= link_to "Edit", edit_board_path(@board) %><br>
    <%= link_to "Delete",board_path(@board), :method => :delete, data: {confirm: "Are you sure?"} %>

  <% end %>
</div>

<hr>
<div align="center">
  <strong><%= link_to "VIEW ALL TOPICS", board_topics_path(@board) %></strong><br>
  <% if @user %>
    <strong><%= link_to "CREATE NEW TOPIC", new_board_topic_path(@board) %></strong>
  <% end %>
</div>
<% @topics.each do |topic| %>
  <small><strong>ID: <%= topic.id %> | <%= topic.created %> | <%= topic.num_of_responses %> R</strong></small>
  <p><%= topic.title %></p>
  <small><%= link_to "Reply", board_topic_path(@board, topic) %></small><br>
  <hr>
<% end %>