config/routes.rb
Rails.application.routes.draw do
  resources :user_topics
  resources :user_boards
  resources :posts
  resources :boards do
    resources :topics
  end
  get '/myposts', to: 'posts#user', as: 'user_posts'
  get '/news', to: 'application#news', as: 'news'
  get '/about', to: 'application#about', as: 'about'
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'
  devise_scope :user do
    get '/auth/:provider/callback', to: 'users/sessions#create'
  end
  Rails.application.routes.draw do
    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end
  

end

app/views/layouts/_error_messages.html.erb
<% if target.errors.any? %>

  <div id="error_explanation">
    <p>
      <%= pluralize(target.errors.count, "error") %> prevented submission
    </p>
    
      <% target.errors.full_messages.each do |msg| %>
	<p>&nbsp;&nbsp;&nbsp;<%= msg %></p>
      <% end %>
   
  </div>
<% end %>

app/views/layouts/_header.html.erb
<ul class="horizontal">
  <div class="container">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "News", news_path %></li>
    <li><%= link_to "Boards", boards_path %></li>
    <li><%= link_to "About", about_path %></li>
    <% if current_user %>
      <li class="u-pull-right"><%= link_to "Logout (#{current_user.email.first(10)}...)", destroy_user_session_path, :method => :delete %></li>
      
      <li class="u-pull-right"><%= link_to "My Posts", user_posts_path %></li>
      <li class="u-pull-right"><%= link_to "My Topics", user_topics_path %></li>

      
    <% else %>
      <li class="u-pull-right"><%= link_to "Sign In", new_user_session_path %></li>
      <li class="u-pull-right"><%= link_to "Sign In With Github", '/auth/github' %></li>
      <li class="u-pull-right"><%= link_to "Create Account", new_user_registration_path %></li>
      
    <% end %>
  </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssessmentApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div align="center">  
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/scriptless.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssessmentApplication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div align="center">  
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>